package ejercicio3;

public class PruebaExcepcion3 {
    public static void main(String[] args) {
        Excepcion3.divide();
        //¿Qué ocurre después de que el programa responde a un error?
        //Continúa la ejecución normal del programa.
    }
}
